build_from:
  aarch64: "ghcr.io/music-assistant/server:latest"
  amd64: "ghcr.io/music-assistant/server:latest"
  armv7: "ghcr.io/music-assistant/server:latest"
  armhf: "ghcr.io/music-assistant/server:latest"
